#ifndef GOOLNN_XMACROS_PRIV_UTILS_POP_H
#define GOOLNN_XMACROS_PRIV_UTILS_POP_H

#include "xmacros/priv/overload.h"

#define priv_pop_front_0(...) __VA_ARGS__
#define priv_pop_front_1(v, ...) priv_pop_front_0(__VA_ARGS__)
#define priv_pop_front_2(v, ...) priv_pop_front_1(__VA_ARGS__)
#define priv_pop_front_3(v, ...) priv_pop_front_2(__VA_ARGS__)
#define priv_pop_front_4(v, ...) priv_pop_front_3(__VA_ARGS__)
#define priv_pop_front_5(v, ...) priv_pop_front_4(__VA_ARGS__)
#define priv_pop_front_6(v, ...) priv_pop_front_5(__VA_ARGS__)
#define priv_pop_front_7(v, ...) priv_pop_front_6(__VA_ARGS__)
#define priv_pop_front_8(v, ...) priv_pop_front_7(__VA_ARGS__)
#define priv_pop_front_9(v, ...) priv_pop_front_8(__VA_ARGS__)
#define priv_pop_front_10(v, ...) priv_pop_front_9(__VA_ARGS__)
#define priv_pop_front_11(v, ...) priv_pop_front_10(__VA_ARGS__)
#define priv_pop_front_12(v, ...) priv_pop_front_11(__VA_ARGS__)
#define priv_pop_front_13(v, ...) priv_pop_front_12(__VA_ARGS__)
#define priv_pop_front_14(v, ...) priv_pop_front_13(__VA_ARGS__)
#define priv_pop_front_15(v, ...) priv_pop_front_14(__VA_ARGS__)
#define priv_pop_front_16(v, ...) priv_pop_front_15(__VA_ARGS__)
#define priv_pop_front_17(v, ...) priv_pop_front_16(__VA_ARGS__)
#define priv_pop_front_18(v, ...) priv_pop_front_17(__VA_ARGS__)
#define priv_pop_front_19(v, ...) priv_pop_front_18(__VA_ARGS__)
#define priv_pop_front_20(v, ...) priv_pop_front_19(__VA_ARGS__)
#define priv_pop_front_21(v, ...) priv_pop_front_20(__VA_ARGS__)
#define priv_pop_front_22(v, ...) priv_pop_front_21(__VA_ARGS__)
#define priv_pop_front_23(v, ...) priv_pop_front_22(__VA_ARGS__)
#define priv_pop_front_24(v, ...) priv_pop_front_23(__VA_ARGS__)
#define priv_pop_front_25(v, ...) priv_pop_front_24(__VA_ARGS__)
#define priv_pop_front_26(v, ...) priv_pop_front_25(__VA_ARGS__)
#define priv_pop_front_27(v, ...) priv_pop_front_26(__VA_ARGS__)
#define priv_pop_front_28(v, ...) priv_pop_front_27(__VA_ARGS__)
#define priv_pop_front_29(v, ...) priv_pop_front_28(__VA_ARGS__)
#define priv_pop_front_30(v, ...) priv_pop_front_29(__VA_ARGS__)
#define priv_pop_front_31(v, ...) priv_pop_front_30(__VA_ARGS__)
#define priv_pop_front_32(v, ...) priv_pop_front_31(__VA_ARGS__)
#define priv_pop_front_33(v, ...) priv_pop_front_32(__VA_ARGS__)
#define priv_pop_front_34(v, ...) priv_pop_front_33(__VA_ARGS__)
#define priv_pop_front_35(v, ...) priv_pop_front_34(__VA_ARGS__)
#define priv_pop_front_36(v, ...) priv_pop_front_35(__VA_ARGS__)
#define priv_pop_front_37(v, ...) priv_pop_front_36(__VA_ARGS__)
#define priv_pop_front_38(v, ...) priv_pop_front_37(__VA_ARGS__)
#define priv_pop_front_39(v, ...) priv_pop_front_38(__VA_ARGS__)
#define priv_pop_front_40(v, ...) priv_pop_front_39(__VA_ARGS__)
#define priv_pop_front_41(v, ...) priv_pop_front_40(__VA_ARGS__)
#define priv_pop_front_42(v, ...) priv_pop_front_41(__VA_ARGS__)
#define priv_pop_front_43(v, ...) priv_pop_front_42(__VA_ARGS__)
#define priv_pop_front_44(v, ...) priv_pop_front_43(__VA_ARGS__)
#define priv_pop_front_45(v, ...) priv_pop_front_44(__VA_ARGS__)
#define priv_pop_front_46(v, ...) priv_pop_front_45(__VA_ARGS__)
#define priv_pop_front_47(v, ...) priv_pop_front_46(__VA_ARGS__)
#define priv_pop_front_48(v, ...) priv_pop_front_47(__VA_ARGS__)
#define priv_pop_front_49(v, ...) priv_pop_front_48(__VA_ARGS__)
#define priv_pop_front_50(v, ...) priv_pop_front_49(__VA_ARGS__)
#define priv_pop_front_51(v, ...) priv_pop_front_50(__VA_ARGS__)
#define priv_pop_front_52(v, ...) priv_pop_front_51(__VA_ARGS__)
#define priv_pop_front_53(v, ...) priv_pop_front_52(__VA_ARGS__)
#define priv_pop_front_54(v, ...) priv_pop_front_53(__VA_ARGS__)
#define priv_pop_front_55(v, ...) priv_pop_front_54(__VA_ARGS__)
#define priv_pop_front_56(v, ...) priv_pop_front_55(__VA_ARGS__)
#define priv_pop_front_57(v, ...) priv_pop_front_56(__VA_ARGS__)
#define priv_pop_front_58(v, ...) priv_pop_front_57(__VA_ARGS__)
#define priv_pop_front_59(v, ...) priv_pop_front_58(__VA_ARGS__)
#define priv_pop_front_60(v, ...) priv_pop_front_59(__VA_ARGS__)
#define priv_pop_front_61(v, ...) priv_pop_front_60(__VA_ARGS__)
#define priv_pop_front_62(v, ...) priv_pop_front_61(__VA_ARGS__)
#define priv_pop_front_63(v, ...) priv_pop_front_62(__VA_ARGS__)

#define priv_pop_front(n, ...) priv_overload(priv_pop_front, n)(__VA_ARGS__)

#endif
