#ifndef GOOLNN_XMACROS_PRIV_UTILS_POP_H
#define GOOLNN_XMACROS_PRIV_UTILS_POP_H

#include "xmacros/priv/overload.h"

#define priv_pop_0(...) __VA_ARGS__
#define priv_pop_1(v, ...) priv_pop_0(__VA_ARGS__)
#define priv_pop_2(v, ...) priv_pop_1(__VA_ARGS__)
#define priv_pop_3(v, ...) priv_pop_2(__VA_ARGS__)
#define priv_pop_4(v, ...) priv_pop_3(__VA_ARGS__)
#define priv_pop_5(v, ...) priv_pop_4(__VA_ARGS__)
#define priv_pop_6(v, ...) priv_pop_5(__VA_ARGS__)
#define priv_pop_7(v, ...) priv_pop_6(__VA_ARGS__)
#define priv_pop_8(v, ...) priv_pop_7(__VA_ARGS__)
#define priv_pop_9(v, ...) priv_pop_8(__VA_ARGS__)
#define priv_pop_10(v, ...) priv_pop_9(__VA_ARGS__)
#define priv_pop_11(v, ...) priv_pop_10(__VA_ARGS__)
#define priv_pop_12(v, ...) priv_pop_11(__VA_ARGS__)
#define priv_pop_13(v, ...) priv_pop_12(__VA_ARGS__)
#define priv_pop_14(v, ...) priv_pop_13(__VA_ARGS__)
#define priv_pop_15(v, ...) priv_pop_14(__VA_ARGS__)
#define priv_pop_16(v, ...) priv_pop_15(__VA_ARGS__)
#define priv_pop_17(v, ...) priv_pop_16(__VA_ARGS__)
#define priv_pop_18(v, ...) priv_pop_17(__VA_ARGS__)
#define priv_pop_19(v, ...) priv_pop_18(__VA_ARGS__)
#define priv_pop_20(v, ...) priv_pop_19(__VA_ARGS__)
#define priv_pop_21(v, ...) priv_pop_20(__VA_ARGS__)
#define priv_pop_22(v, ...) priv_pop_21(__VA_ARGS__)
#define priv_pop_23(v, ...) priv_pop_22(__VA_ARGS__)
#define priv_pop_24(v, ...) priv_pop_23(__VA_ARGS__)
#define priv_pop_25(v, ...) priv_pop_24(__VA_ARGS__)
#define priv_pop_26(v, ...) priv_pop_25(__VA_ARGS__)
#define priv_pop_27(v, ...) priv_pop_26(__VA_ARGS__)
#define priv_pop_28(v, ...) priv_pop_27(__VA_ARGS__)
#define priv_pop_29(v, ...) priv_pop_28(__VA_ARGS__)
#define priv_pop_30(v, ...) priv_pop_29(__VA_ARGS__)
#define priv_pop_31(v, ...) priv_pop_30(__VA_ARGS__)
#define priv_pop_32(v, ...) priv_pop_31(__VA_ARGS__)
#define priv_pop_33(v, ...) priv_pop_32(__VA_ARGS__)
#define priv_pop_34(v, ...) priv_pop_33(__VA_ARGS__)
#define priv_pop_35(v, ...) priv_pop_34(__VA_ARGS__)
#define priv_pop_36(v, ...) priv_pop_35(__VA_ARGS__)
#define priv_pop_37(v, ...) priv_pop_36(__VA_ARGS__)
#define priv_pop_38(v, ...) priv_pop_37(__VA_ARGS__)
#define priv_pop_39(v, ...) priv_pop_38(__VA_ARGS__)
#define priv_pop_40(v, ...) priv_pop_39(__VA_ARGS__)
#define priv_pop_41(v, ...) priv_pop_40(__VA_ARGS__)
#define priv_pop_42(v, ...) priv_pop_41(__VA_ARGS__)
#define priv_pop_43(v, ...) priv_pop_42(__VA_ARGS__)
#define priv_pop_44(v, ...) priv_pop_43(__VA_ARGS__)
#define priv_pop_45(v, ...) priv_pop_44(__VA_ARGS__)
#define priv_pop_46(v, ...) priv_pop_45(__VA_ARGS__)
#define priv_pop_47(v, ...) priv_pop_46(__VA_ARGS__)
#define priv_pop_48(v, ...) priv_pop_47(__VA_ARGS__)
#define priv_pop_49(v, ...) priv_pop_48(__VA_ARGS__)
#define priv_pop_50(v, ...) priv_pop_49(__VA_ARGS__)
#define priv_pop_51(v, ...) priv_pop_50(__VA_ARGS__)
#define priv_pop_52(v, ...) priv_pop_51(__VA_ARGS__)
#define priv_pop_53(v, ...) priv_pop_52(__VA_ARGS__)
#define priv_pop_54(v, ...) priv_pop_53(__VA_ARGS__)
#define priv_pop_55(v, ...) priv_pop_54(__VA_ARGS__)
#define priv_pop_56(v, ...) priv_pop_55(__VA_ARGS__)
#define priv_pop_57(v, ...) priv_pop_56(__VA_ARGS__)
#define priv_pop_58(v, ...) priv_pop_57(__VA_ARGS__)
#define priv_pop_59(v, ...) priv_pop_58(__VA_ARGS__)
#define priv_pop_60(v, ...) priv_pop_59(__VA_ARGS__)
#define priv_pop_61(v, ...) priv_pop_60(__VA_ARGS__)
#define priv_pop_62(v, ...) priv_pop_61(__VA_ARGS__)
#define priv_pop_63(v, ...) priv_pop_62(__VA_ARGS__)

#define priv_pop(n, ...) priv_overload(priv_pop, n)(__VA_ARGS__)

#endif
