#ifndef GOOLNN_XMACROS_PRIV_COMBINE_H
#define GOOLNN_XMACROS_PRIV_COMBINE_H

#include "xmacros/priv/overload.h"

#define priv_apply_combine(a, b) a ## _ ## b

#define priv_combine_0()
#define priv_combine_1(v) v
#define priv_combine_2(a, b) priv_apply_combine(a, b)
#define priv_combine_3(v, ...) priv_combine_2(v, priv_combine_2(__VA_ARGS__))
#define priv_combine_4(v, ...) priv_combine_2(v, priv_combine_3(__VA_ARGS__))
#define priv_combine_5(v, ...) priv_combine_2(v, priv_combine_4(__VA_ARGS__))
#define priv_combine_6(v, ...) priv_combine_2(v, priv_combine_5(__VA_ARGS__))
#define priv_combine_7(v, ...) priv_combine_2(v, priv_combine_6(__VA_ARGS__))
#define priv_combine_8(v, ...) priv_combine_2(v, priv_combine_7(__VA_ARGS__))
#define priv_combine_9(v, ...) priv_combine_2(v, priv_combine_8(__VA_ARGS__))
#define priv_combine_10(v, ...) priv_combine_2(v, priv_combine_9(__VA_ARGS__))
#define priv_combine_11(v, ...) priv_combine_2(v, priv_combine_10(__VA_ARGS__))
#define priv_combine_12(v, ...) priv_combine_2(v, priv_combine_11(__VA_ARGS__))
#define priv_combine_13(v, ...) priv_combine_2(v, priv_combine_12(__VA_ARGS__))
#define priv_combine_14(v, ...) priv_combine_2(v, priv_combine_13(__VA_ARGS__))
#define priv_combine_15(v, ...) priv_combine_2(v, priv_combine_14(__VA_ARGS__))
#define priv_combine_16(v, ...) priv_combine_2(v, priv_combine_15(__VA_ARGS__))
#define priv_combine_17(v, ...) priv_combine_2(v, priv_combine_16(__VA_ARGS__))
#define priv_combine_18(v, ...) priv_combine_2(v, priv_combine_17(__VA_ARGS__))
#define priv_combine_19(v, ...) priv_combine_2(v, priv_combine_18(__VA_ARGS__))
#define priv_combine_20(v, ...) priv_combine_2(v, priv_combine_19(__VA_ARGS__))
#define priv_combine_21(v, ...) priv_combine_2(v, priv_combine_20(__VA_ARGS__))
#define priv_combine_22(v, ...) priv_combine_2(v, priv_combine_21(__VA_ARGS__))
#define priv_combine_23(v, ...) priv_combine_2(v, priv_combine_22(__VA_ARGS__))
#define priv_combine_24(v, ...) priv_combine_2(v, priv_combine_23(__VA_ARGS__))
#define priv_combine_25(v, ...) priv_combine_2(v, priv_combine_24(__VA_ARGS__))
#define priv_combine_26(v, ...) priv_combine_2(v, priv_combine_25(__VA_ARGS__))
#define priv_combine_27(v, ...) priv_combine_2(v, priv_combine_26(__VA_ARGS__))
#define priv_combine_28(v, ...) priv_combine_2(v, priv_combine_27(__VA_ARGS__))
#define priv_combine_29(v, ...) priv_combine_2(v, priv_combine_28(__VA_ARGS__))
#define priv_combine_30(v, ...) priv_combine_2(v, priv_combine_29(__VA_ARGS__))
#define priv_combine_31(v, ...) priv_combine_2(v, priv_combine_30(__VA_ARGS__))
#define priv_combine_32(v, ...) priv_combine_2(v, priv_combine_31(__VA_ARGS__))
#define priv_combine_33(v, ...) priv_combine_2(v, priv_combine_32(__VA_ARGS__))
#define priv_combine_34(v, ...) priv_combine_2(v, priv_combine_33(__VA_ARGS__))
#define priv_combine_35(v, ...) priv_combine_2(v, priv_combine_34(__VA_ARGS__))
#define priv_combine_36(v, ...) priv_combine_2(v, priv_combine_35(__VA_ARGS__))
#define priv_combine_37(v, ...) priv_combine_2(v, priv_combine_36(__VA_ARGS__))
#define priv_combine_38(v, ...) priv_combine_2(v, priv_combine_37(__VA_ARGS__))
#define priv_combine_39(v, ...) priv_combine_2(v, priv_combine_38(__VA_ARGS__))
#define priv_combine_40(v, ...) priv_combine_2(v, priv_combine_39(__VA_ARGS__))
#define priv_combine_41(v, ...) priv_combine_2(v, priv_combine_40(__VA_ARGS__))
#define priv_combine_42(v, ...) priv_combine_2(v, priv_combine_41(__VA_ARGS__))
#define priv_combine_43(v, ...) priv_combine_2(v, priv_combine_42(__VA_ARGS__))
#define priv_combine_44(v, ...) priv_combine_2(v, priv_combine_43(__VA_ARGS__))
#define priv_combine_45(v, ...) priv_combine_2(v, priv_combine_44(__VA_ARGS__))
#define priv_combine_46(v, ...) priv_combine_2(v, priv_combine_45(__VA_ARGS__))
#define priv_combine_47(v, ...) priv_combine_2(v, priv_combine_46(__VA_ARGS__))
#define priv_combine_48(v, ...) priv_combine_2(v, priv_combine_47(__VA_ARGS__))
#define priv_combine_49(v, ...) priv_combine_2(v, priv_combine_48(__VA_ARGS__))
#define priv_combine_50(v, ...) priv_combine_2(v, priv_combine_49(__VA_ARGS__))
#define priv_combine_51(v, ...) priv_combine_2(v, priv_combine_50(__VA_ARGS__))
#define priv_combine_52(v, ...) priv_combine_2(v, priv_combine_51(__VA_ARGS__))
#define priv_combine_53(v, ...) priv_combine_2(v, priv_combine_52(__VA_ARGS__))
#define priv_combine_54(v, ...) priv_combine_2(v, priv_combine_53(__VA_ARGS__))
#define priv_combine_55(v, ...) priv_combine_2(v, priv_combine_54(__VA_ARGS__))
#define priv_combine_56(v, ...) priv_combine_2(v, priv_combine_55(__VA_ARGS__))
#define priv_combine_57(v, ...) priv_combine_2(v, priv_combine_56(__VA_ARGS__))
#define priv_combine_58(v, ...) priv_combine_2(v, priv_combine_57(__VA_ARGS__))
#define priv_combine_59(v, ...) priv_combine_2(v, priv_combine_58(__VA_ARGS__))
#define priv_combine_60(v, ...) priv_combine_2(v, priv_combine_59(__VA_ARGS__))
#define priv_combine_61(v, ...) priv_combine_2(v, priv_combine_60(__VA_ARGS__))
#define priv_combine_62(v, ...) priv_combine_2(v, priv_combine_61(__VA_ARGS__))
#define priv_combine_63(v, ...) priv_combine_2(v, priv_combine_62(__VA_ARGS__))

#define priv_combine(...) priv_overload(priv_combine, priv_argc(__VA_ARGS__))(__VA_ARGS__)

#endif
