#ifndef GOOLNN_XMACROS_PRIV_CONCAT_H
#define GOOLNN_XMACROS_PRIV_CONCAT_H

#include "xmacros/priv/overload.h"

#define priv_apply_concat(a, b) a ## b

#define priv_concat_0()
#define priv_concat_1(v) v
#define priv_concat_2(a, b) priv_apply_concat(a, b)
#define priv_concat_3(v, ...) priv_concat_2(v, priv_concat_2(__VA_ARGS__))
#define priv_concat_4(v, ...) priv_concat_2(v, priv_concat_3(__VA_ARGS__))
#define priv_concat_5(v, ...) priv_concat_2(v, priv_concat_4(__VA_ARGS__))
#define priv_concat_6(v, ...) priv_concat_2(v, priv_concat_5(__VA_ARGS__))
#define priv_concat_7(v, ...) priv_concat_2(v, priv_concat_6(__VA_ARGS__))
#define priv_concat_8(v, ...) priv_concat_2(v, priv_concat_7(__VA_ARGS__))
#define priv_concat_9(v, ...) priv_concat_2(v, priv_concat_8(__VA_ARGS__))
#define priv_concat_10(v, ...) priv_concat_2(v, priv_concat_9(__VA_ARGS__))
#define priv_concat_11(v, ...) priv_concat_2(v, priv_concat_10(__VA_ARGS__))
#define priv_concat_12(v, ...) priv_concat_2(v, priv_concat_11(__VA_ARGS__))
#define priv_concat_13(v, ...) priv_concat_2(v, priv_concat_12(__VA_ARGS__))
#define priv_concat_14(v, ...) priv_concat_2(v, priv_concat_13(__VA_ARGS__))
#define priv_concat_15(v, ...) priv_concat_2(v, priv_concat_14(__VA_ARGS__))
#define priv_concat_16(v, ...) priv_concat_2(v, priv_concat_15(__VA_ARGS__))
#define priv_concat_17(v, ...) priv_concat_2(v, priv_concat_16(__VA_ARGS__))
#define priv_concat_18(v, ...) priv_concat_2(v, priv_concat_17(__VA_ARGS__))
#define priv_concat_19(v, ...) priv_concat_2(v, priv_concat_18(__VA_ARGS__))
#define priv_concat_20(v, ...) priv_concat_2(v, priv_concat_19(__VA_ARGS__))
#define priv_concat_21(v, ...) priv_concat_2(v, priv_concat_20(__VA_ARGS__))
#define priv_concat_22(v, ...) priv_concat_2(v, priv_concat_21(__VA_ARGS__))
#define priv_concat_23(v, ...) priv_concat_2(v, priv_concat_22(__VA_ARGS__))
#define priv_concat_24(v, ...) priv_concat_2(v, priv_concat_23(__VA_ARGS__))
#define priv_concat_25(v, ...) priv_concat_2(v, priv_concat_24(__VA_ARGS__))
#define priv_concat_26(v, ...) priv_concat_2(v, priv_concat_25(__VA_ARGS__))
#define priv_concat_27(v, ...) priv_concat_2(v, priv_concat_26(__VA_ARGS__))
#define priv_concat_28(v, ...) priv_concat_2(v, priv_concat_27(__VA_ARGS__))
#define priv_concat_29(v, ...) priv_concat_2(v, priv_concat_28(__VA_ARGS__))
#define priv_concat_30(v, ...) priv_concat_2(v, priv_concat_29(__VA_ARGS__))
#define priv_concat_31(v, ...) priv_concat_2(v, priv_concat_30(__VA_ARGS__))
#define priv_concat_32(v, ...) priv_concat_2(v, priv_concat_31(__VA_ARGS__))
#define priv_concat_33(v, ...) priv_concat_2(v, priv_concat_32(__VA_ARGS__))
#define priv_concat_34(v, ...) priv_concat_2(v, priv_concat_33(__VA_ARGS__))
#define priv_concat_35(v, ...) priv_concat_2(v, priv_concat_34(__VA_ARGS__))
#define priv_concat_36(v, ...) priv_concat_2(v, priv_concat_35(__VA_ARGS__))
#define priv_concat_37(v, ...) priv_concat_2(v, priv_concat_36(__VA_ARGS__))
#define priv_concat_38(v, ...) priv_concat_2(v, priv_concat_37(__VA_ARGS__))
#define priv_concat_39(v, ...) priv_concat_2(v, priv_concat_38(__VA_ARGS__))
#define priv_concat_40(v, ...) priv_concat_2(v, priv_concat_39(__VA_ARGS__))
#define priv_concat_41(v, ...) priv_concat_2(v, priv_concat_40(__VA_ARGS__))
#define priv_concat_42(v, ...) priv_concat_2(v, priv_concat_41(__VA_ARGS__))
#define priv_concat_43(v, ...) priv_concat_2(v, priv_concat_42(__VA_ARGS__))
#define priv_concat_44(v, ...) priv_concat_2(v, priv_concat_43(__VA_ARGS__))
#define priv_concat_45(v, ...) priv_concat_2(v, priv_concat_44(__VA_ARGS__))
#define priv_concat_46(v, ...) priv_concat_2(v, priv_concat_45(__VA_ARGS__))
#define priv_concat_47(v, ...) priv_concat_2(v, priv_concat_46(__VA_ARGS__))
#define priv_concat_48(v, ...) priv_concat_2(v, priv_concat_47(__VA_ARGS__))
#define priv_concat_49(v, ...) priv_concat_2(v, priv_concat_48(__VA_ARGS__))
#define priv_concat_50(v, ...) priv_concat_2(v, priv_concat_49(__VA_ARGS__))
#define priv_concat_51(v, ...) priv_concat_2(v, priv_concat_50(__VA_ARGS__))
#define priv_concat_52(v, ...) priv_concat_2(v, priv_concat_51(__VA_ARGS__))
#define priv_concat_53(v, ...) priv_concat_2(v, priv_concat_52(__VA_ARGS__))
#define priv_concat_54(v, ...) priv_concat_2(v, priv_concat_53(__VA_ARGS__))
#define priv_concat_55(v, ...) priv_concat_2(v, priv_concat_54(__VA_ARGS__))
#define priv_concat_56(v, ...) priv_concat_2(v, priv_concat_55(__VA_ARGS__))
#define priv_concat_57(v, ...) priv_concat_2(v, priv_concat_56(__VA_ARGS__))
#define priv_concat_58(v, ...) priv_concat_2(v, priv_concat_57(__VA_ARGS__))
#define priv_concat_59(v, ...) priv_concat_2(v, priv_concat_58(__VA_ARGS__))
#define priv_concat_60(v, ...) priv_concat_2(v, priv_concat_59(__VA_ARGS__))
#define priv_concat_61(v, ...) priv_concat_2(v, priv_concat_60(__VA_ARGS__))
#define priv_concat_62(v, ...) priv_concat_2(v, priv_concat_61(__VA_ARGS__))
#define priv_concat_63(v, ...) priv_concat_2(v, priv_concat_62(__VA_ARGS__))

#define priv_concat(...) priv_overload(priv_concat, priv_argc(__VA_ARGS__))(__VA_ARGS__)

#endif
