#ifndef GOOLNN_XMACROS_PRIV_JOIN_H
#define GOOLNN_XMACROS_PRIV_JOIN_H

#include "xmacros/priv/overload.h"

#define priv_apply_join(sep, a, b) a ## sep ## b

#define priv_join_0(sep)
#define priv_join_1(sep, v) v
#define priv_join_2(sep, a, b) priv_apply_join(sep, a, b)
#define priv_join_3(sep, v, ...) priv_join_2(sep, v, priv_join_2(sep, __VA_ARGS__))
#define priv_join_4(sep, v, ...) priv_join_2(sep, v, priv_join_3(sep, __VA_ARGS__))
#define priv_join_5(sep, v, ...) priv_join_2(sep, v, priv_join_4(sep, __VA_ARGS__))
#define priv_join_6(sep, v, ...) priv_join_2(sep, v, priv_join_5(sep, __VA_ARGS__))
#define priv_join_7(sep, v, ...) priv_join_2(sep, v, priv_join_6(sep, __VA_ARGS__))
#define priv_join_8(sep, v, ...) priv_join_2(sep, v, priv_join_7(sep, __VA_ARGS__))
#define priv_join_9(sep, v, ...) priv_join_2(sep, v, priv_join_8(sep, __VA_ARGS__))
#define priv_join_10(sep, v, ...) priv_join_2(sep, v, priv_join_9(sep, __VA_ARGS__))
#define priv_join_11(sep, v, ...) priv_join_2(sep, v, priv_join_10(sep, __VA_ARGS__))
#define priv_join_12(sep, v, ...) priv_join_2(sep, v, priv_join_11(sep, __VA_ARGS__))
#define priv_join_13(sep, v, ...) priv_join_2(sep, v, priv_join_12(sep, __VA_ARGS__))
#define priv_join_14(sep, v, ...) priv_join_2(sep, v, priv_join_13(sep, __VA_ARGS__))
#define priv_join_15(sep, v, ...) priv_join_2(sep, v, priv_join_14(sep, __VA_ARGS__))
#define priv_join_16(sep, v, ...) priv_join_2(sep, v, priv_join_15(sep, __VA_ARGS__))
#define priv_join_17(sep, v, ...) priv_join_2(sep, v, priv_join_16(sep, __VA_ARGS__))
#define priv_join_18(sep, v, ...) priv_join_2(sep, v, priv_join_17(sep, __VA_ARGS__))
#define priv_join_19(sep, v, ...) priv_join_2(sep, v, priv_join_18(sep, __VA_ARGS__))
#define priv_join_20(sep, v, ...) priv_join_2(sep, v, priv_join_19(sep, __VA_ARGS__))
#define priv_join_21(sep, v, ...) priv_join_2(sep, v, priv_join_20(sep, __VA_ARGS__))
#define priv_join_22(sep, v, ...) priv_join_2(sep, v, priv_join_21(sep, __VA_ARGS__))
#define priv_join_23(sep, v, ...) priv_join_2(sep, v, priv_join_22(sep, __VA_ARGS__))
#define priv_join_24(sep, v, ...) priv_join_2(sep, v, priv_join_23(sep, __VA_ARGS__))
#define priv_join_25(sep, v, ...) priv_join_2(sep, v, priv_join_24(sep, __VA_ARGS__))
#define priv_join_26(sep, v, ...) priv_join_2(sep, v, priv_join_25(sep, __VA_ARGS__))
#define priv_join_27(sep, v, ...) priv_join_2(sep, v, priv_join_26(sep, __VA_ARGS__))
#define priv_join_28(sep, v, ...) priv_join_2(sep, v, priv_join_27(sep, __VA_ARGS__))
#define priv_join_29(sep, v, ...) priv_join_2(sep, v, priv_join_28(sep, __VA_ARGS__))
#define priv_join_30(sep, v, ...) priv_join_2(sep, v, priv_join_29(sep, __VA_ARGS__))
#define priv_join_31(sep, v, ...) priv_join_2(sep, v, priv_join_30(sep, __VA_ARGS__))
#define priv_join_32(sep, v, ...) priv_join_2(sep, v, priv_join_31(sep, __VA_ARGS__))
#define priv_join_33(sep, v, ...) priv_join_2(sep, v, priv_join_32(sep, __VA_ARGS__))
#define priv_join_34(sep, v, ...) priv_join_2(sep, v, priv_join_33(sep, __VA_ARGS__))
#define priv_join_35(sep, v, ...) priv_join_2(sep, v, priv_join_34(sep, __VA_ARGS__))
#define priv_join_36(sep, v, ...) priv_join_2(sep, v, priv_join_35(sep, __VA_ARGS__))
#define priv_join_37(sep, v, ...) priv_join_2(sep, v, priv_join_36(sep, __VA_ARGS__))
#define priv_join_38(sep, v, ...) priv_join_2(sep, v, priv_join_37(sep, __VA_ARGS__))
#define priv_join_39(sep, v, ...) priv_join_2(sep, v, priv_join_38(sep, __VA_ARGS__))
#define priv_join_40(sep, v, ...) priv_join_2(sep, v, priv_join_39(sep, __VA_ARGS__))
#define priv_join_41(sep, v, ...) priv_join_2(sep, v, priv_join_40(sep, __VA_ARGS__))
#define priv_join_42(sep, v, ...) priv_join_2(sep, v, priv_join_41(sep, __VA_ARGS__))
#define priv_join_43(sep, v, ...) priv_join_2(sep, v, priv_join_42(sep, __VA_ARGS__))
#define priv_join_44(sep, v, ...) priv_join_2(sep, v, priv_join_43(sep, __VA_ARGS__))
#define priv_join_45(sep, v, ...) priv_join_2(sep, v, priv_join_44(sep, __VA_ARGS__))
#define priv_join_46(sep, v, ...) priv_join_2(sep, v, priv_join_45(sep, __VA_ARGS__))
#define priv_join_47(sep, v, ...) priv_join_2(sep, v, priv_join_46(sep, __VA_ARGS__))
#define priv_join_48(sep, v, ...) priv_join_2(sep, v, priv_join_47(sep, __VA_ARGS__))
#define priv_join_49(sep, v, ...) priv_join_2(sep, v, priv_join_48(sep, __VA_ARGS__))
#define priv_join_50(sep, v, ...) priv_join_2(sep, v, priv_join_49(sep, __VA_ARGS__))
#define priv_join_51(sep, v, ...) priv_join_2(sep, v, priv_join_50(sep, __VA_ARGS__))
#define priv_join_52(sep, v, ...) priv_join_2(sep, v, priv_join_51(sep, __VA_ARGS__))
#define priv_join_53(sep, v, ...) priv_join_2(sep, v, priv_join_52(sep, __VA_ARGS__))
#define priv_join_54(sep, v, ...) priv_join_2(sep, v, priv_join_53(sep, __VA_ARGS__))
#define priv_join_55(sep, v, ...) priv_join_2(sep, v, priv_join_54(sep, __VA_ARGS__))
#define priv_join_56(sep, v, ...) priv_join_2(sep, v, priv_join_55(sep, __VA_ARGS__))
#define priv_join_57(sep, v, ...) priv_join_2(sep, v, priv_join_56(sep, __VA_ARGS__))
#define priv_join_58(sep, v, ...) priv_join_2(sep, v, priv_join_57(sep, __VA_ARGS__))
#define priv_join_59(sep, v, ...) priv_join_2(sep, v, priv_join_58(sep, __VA_ARGS__))
#define priv_join_60(sep, v, ...) priv_join_2(sep, v, priv_join_59(sep, __VA_ARGS__))
#define priv_join_61(sep, v, ...) priv_join_2(sep, v, priv_join_60(sep, __VA_ARGS__))
#define priv_join_62(sep, v, ...) priv_join_2(sep, v, priv_join_61(sep, __VA_ARGS__))
#define priv_join_63(sep, v, ...) priv_join_2(sep, v, priv_join_62(sep, __VA_ARGS__))

#define priv_join(sep, ...) priv_overload(priv_join, priv_argc(__VA_ARGS__))(sep, __VA_ARGS__)

#endif
