#ifndef GOOLNN_XMACROS_PRIV_PREFIX_H
#define GOOLNN_XMACROS_PRIV_PREFIX_H

#include "xmacros/priv/overload.h"
#include "xmacros/priv/combine.h"
#include "xmacros/priv/concat.h"
#include "xmacros/priv/join.h"

#define priv_prefix_combine_0(pre, ...)
#define priv_prefix_combine_1(pre, v, ...) priv_combine_2(pre, v)
#define priv_prefix_combine_2(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_1(pre, __VA_ARGS__)
#define priv_prefix_combine_3(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_2(pre, __VA_ARGS__)
#define priv_prefix_combine_4(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_3(pre, __VA_ARGS__)
#define priv_prefix_combine_5(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_4(pre, __VA_ARGS__)
#define priv_prefix_combine_6(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_5(pre, __VA_ARGS__)
#define priv_prefix_combine_7(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_6(pre, __VA_ARGS__)
#define priv_prefix_combine_8(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_7(pre, __VA_ARGS__)
#define priv_prefix_combine_9(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_8(pre, __VA_ARGS__)
#define priv_prefix_combine_10(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_9(pre, __VA_ARGS__)
#define priv_prefix_combine_11(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_10(pre, __VA_ARGS__)
#define priv_prefix_combine_12(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_11(pre, __VA_ARGS__)
#define priv_prefix_combine_13(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_12(pre, __VA_ARGS__)
#define priv_prefix_combine_14(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_13(pre, __VA_ARGS__)
#define priv_prefix_combine_15(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_14(pre, __VA_ARGS__)
#define priv_prefix_combine_16(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_15(pre, __VA_ARGS__)
#define priv_prefix_combine_17(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_16(pre, __VA_ARGS__)
#define priv_prefix_combine_18(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_17(pre, __VA_ARGS__)
#define priv_prefix_combine_19(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_18(pre, __VA_ARGS__)
#define priv_prefix_combine_20(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_19(pre, __VA_ARGS__)
#define priv_prefix_combine_21(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_20(pre, __VA_ARGS__)
#define priv_prefix_combine_22(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_21(pre, __VA_ARGS__)
#define priv_prefix_combine_23(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_22(pre, __VA_ARGS__)
#define priv_prefix_combine_24(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_23(pre, __VA_ARGS__)
#define priv_prefix_combine_25(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_24(pre, __VA_ARGS__)
#define priv_prefix_combine_26(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_25(pre, __VA_ARGS__)
#define priv_prefix_combine_27(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_26(pre, __VA_ARGS__)
#define priv_prefix_combine_28(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_27(pre, __VA_ARGS__)
#define priv_prefix_combine_29(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_28(pre, __VA_ARGS__)
#define priv_prefix_combine_30(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_29(pre, __VA_ARGS__)
#define priv_prefix_combine_31(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_30(pre, __VA_ARGS__)
#define priv_prefix_combine_32(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_31(pre, __VA_ARGS__)
#define priv_prefix_combine_33(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_32(pre, __VA_ARGS__)
#define priv_prefix_combine_34(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_33(pre, __VA_ARGS__)
#define priv_prefix_combine_35(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_34(pre, __VA_ARGS__)
#define priv_prefix_combine_36(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_35(pre, __VA_ARGS__)
#define priv_prefix_combine_37(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_36(pre, __VA_ARGS__)
#define priv_prefix_combine_38(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_37(pre, __VA_ARGS__)
#define priv_prefix_combine_39(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_38(pre, __VA_ARGS__)
#define priv_prefix_combine_40(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_39(pre, __VA_ARGS__)
#define priv_prefix_combine_41(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_40(pre, __VA_ARGS__)
#define priv_prefix_combine_42(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_41(pre, __VA_ARGS__)
#define priv_prefix_combine_43(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_42(pre, __VA_ARGS__)
#define priv_prefix_combine_44(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_43(pre, __VA_ARGS__)
#define priv_prefix_combine_45(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_44(pre, __VA_ARGS__)
#define priv_prefix_combine_46(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_45(pre, __VA_ARGS__)
#define priv_prefix_combine_47(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_46(pre, __VA_ARGS__)
#define priv_prefix_combine_48(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_47(pre, __VA_ARGS__)
#define priv_prefix_combine_49(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_48(pre, __VA_ARGS__)
#define priv_prefix_combine_50(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_49(pre, __VA_ARGS__)
#define priv_prefix_combine_51(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_50(pre, __VA_ARGS__)
#define priv_prefix_combine_52(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_51(pre, __VA_ARGS__)
#define priv_prefix_combine_53(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_52(pre, __VA_ARGS__)
#define priv_prefix_combine_54(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_53(pre, __VA_ARGS__)
#define priv_prefix_combine_55(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_54(pre, __VA_ARGS__)
#define priv_prefix_combine_56(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_55(pre, __VA_ARGS__)
#define priv_prefix_combine_57(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_56(pre, __VA_ARGS__)
#define priv_prefix_combine_58(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_57(pre, __VA_ARGS__)
#define priv_prefix_combine_59(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_58(pre, __VA_ARGS__)
#define priv_prefix_combine_60(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_59(pre, __VA_ARGS__)
#define priv_prefix_combine_61(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_60(pre, __VA_ARGS__)
#define priv_prefix_combine_62(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_61(pre, __VA_ARGS__)
#define priv_prefix_combine_63(pre, v, ...) priv_combine_2(pre, v), priv_prefix_combine_62(pre, __VA_ARGS__)

#define priv_prefix_concat_0(pre, ...)
#define priv_prefix_concat_1(pre, v, ...) priv_concat_2(pre, v)
#define priv_prefix_concat_2(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_1(pre, __VA_ARGS__)
#define priv_prefix_concat_3(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_2(pre, __VA_ARGS__)
#define priv_prefix_concat_4(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_3(pre, __VA_ARGS__)
#define priv_prefix_concat_5(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_4(pre, __VA_ARGS__)
#define priv_prefix_concat_6(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_5(pre, __VA_ARGS__)
#define priv_prefix_concat_7(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_6(pre, __VA_ARGS__)
#define priv_prefix_concat_8(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_7(pre, __VA_ARGS__)
#define priv_prefix_concat_9(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_8(pre, __VA_ARGS__)
#define priv_prefix_concat_10(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_9(pre, __VA_ARGS__)
#define priv_prefix_concat_11(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_10(pre, __VA_ARGS__)
#define priv_prefix_concat_12(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_11(pre, __VA_ARGS__)
#define priv_prefix_concat_13(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_12(pre, __VA_ARGS__)
#define priv_prefix_concat_14(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_13(pre, __VA_ARGS__)
#define priv_prefix_concat_15(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_14(pre, __VA_ARGS__)
#define priv_prefix_concat_16(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_15(pre, __VA_ARGS__)
#define priv_prefix_concat_17(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_16(pre, __VA_ARGS__)
#define priv_prefix_concat_18(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_17(pre, __VA_ARGS__)
#define priv_prefix_concat_19(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_18(pre, __VA_ARGS__)
#define priv_prefix_concat_20(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_19(pre, __VA_ARGS__)
#define priv_prefix_concat_21(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_20(pre, __VA_ARGS__)
#define priv_prefix_concat_22(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_21(pre, __VA_ARGS__)
#define priv_prefix_concat_23(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_22(pre, __VA_ARGS__)
#define priv_prefix_concat_24(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_23(pre, __VA_ARGS__)
#define priv_prefix_concat_25(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_24(pre, __VA_ARGS__)
#define priv_prefix_concat_26(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_25(pre, __VA_ARGS__)
#define priv_prefix_concat_27(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_26(pre, __VA_ARGS__)
#define priv_prefix_concat_28(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_27(pre, __VA_ARGS__)
#define priv_prefix_concat_29(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_28(pre, __VA_ARGS__)
#define priv_prefix_concat_30(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_29(pre, __VA_ARGS__)
#define priv_prefix_concat_31(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_30(pre, __VA_ARGS__)
#define priv_prefix_concat_32(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_31(pre, __VA_ARGS__)
#define priv_prefix_concat_33(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_32(pre, __VA_ARGS__)
#define priv_prefix_concat_34(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_33(pre, __VA_ARGS__)
#define priv_prefix_concat_35(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_34(pre, __VA_ARGS__)
#define priv_prefix_concat_36(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_35(pre, __VA_ARGS__)
#define priv_prefix_concat_37(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_36(pre, __VA_ARGS__)
#define priv_prefix_concat_38(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_37(pre, __VA_ARGS__)
#define priv_prefix_concat_39(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_38(pre, __VA_ARGS__)
#define priv_prefix_concat_40(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_39(pre, __VA_ARGS__)
#define priv_prefix_concat_41(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_40(pre, __VA_ARGS__)
#define priv_prefix_concat_42(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_41(pre, __VA_ARGS__)
#define priv_prefix_concat_43(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_42(pre, __VA_ARGS__)
#define priv_prefix_concat_44(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_43(pre, __VA_ARGS__)
#define priv_prefix_concat_45(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_44(pre, __VA_ARGS__)
#define priv_prefix_concat_46(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_45(pre, __VA_ARGS__)
#define priv_prefix_concat_47(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_46(pre, __VA_ARGS__)
#define priv_prefix_concat_48(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_47(pre, __VA_ARGS__)
#define priv_prefix_concat_49(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_48(pre, __VA_ARGS__)
#define priv_prefix_concat_50(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_49(pre, __VA_ARGS__)
#define priv_prefix_concat_51(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_50(pre, __VA_ARGS__)
#define priv_prefix_concat_52(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_51(pre, __VA_ARGS__)
#define priv_prefix_concat_53(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_52(pre, __VA_ARGS__)
#define priv_prefix_concat_54(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_53(pre, __VA_ARGS__)
#define priv_prefix_concat_55(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_54(pre, __VA_ARGS__)
#define priv_prefix_concat_56(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_55(pre, __VA_ARGS__)
#define priv_prefix_concat_57(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_56(pre, __VA_ARGS__)
#define priv_prefix_concat_58(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_57(pre, __VA_ARGS__)
#define priv_prefix_concat_59(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_58(pre, __VA_ARGS__)
#define priv_prefix_concat_60(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_59(pre, __VA_ARGS__)
#define priv_prefix_concat_61(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_60(pre, __VA_ARGS__)
#define priv_prefix_concat_62(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_61(pre, __VA_ARGS__)
#define priv_prefix_concat_63(pre, v, ...) priv_concat_2(pre, v), priv_prefix_concat_62(pre, __VA_ARGS__)

#define priv_prefix_join_0(pre, sep, ...)
#define priv_prefix_join_1(pre, sep, v, ...) priv_join_2(sep, pre, v)
#define priv_prefix_join_2(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_1(pre, sep, __VA_ARGS__)
#define priv_prefix_join_3(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_2(pre, sep, __VA_ARGS__)
#define priv_prefix_join_4(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_3(pre, sep, __VA_ARGS__)
#define priv_prefix_join_5(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_4(pre, sep, __VA_ARGS__)
#define priv_prefix_join_6(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_5(pre, sep, __VA_ARGS__)
#define priv_prefix_join_7(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_6(pre, sep, __VA_ARGS__)
#define priv_prefix_join_8(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_7(pre, sep, __VA_ARGS__)
#define priv_prefix_join_9(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_8(pre, sep, __VA_ARGS__)
#define priv_prefix_join_10(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_9(pre, sep, __VA_ARGS__)
#define priv_prefix_join_11(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_10(pre, sep, __VA_ARGS__)
#define priv_prefix_join_12(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_11(pre, sep, __VA_ARGS__)
#define priv_prefix_join_13(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_12(pre, sep, __VA_ARGS__)
#define priv_prefix_join_14(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_13(pre, sep, __VA_ARGS__)
#define priv_prefix_join_15(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_14(pre, sep, __VA_ARGS__)
#define priv_prefix_join_16(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_15(pre, sep, __VA_ARGS__)
#define priv_prefix_join_17(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_16(pre, sep, __VA_ARGS__)
#define priv_prefix_join_18(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_17(pre, sep, __VA_ARGS__)
#define priv_prefix_join_19(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_18(pre, sep, __VA_ARGS__)
#define priv_prefix_join_20(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_19(pre, sep, __VA_ARGS__)
#define priv_prefix_join_21(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_20(pre, sep, __VA_ARGS__)
#define priv_prefix_join_22(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_21(pre, sep, __VA_ARGS__)
#define priv_prefix_join_23(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_22(pre, sep, __VA_ARGS__)
#define priv_prefix_join_24(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_23(pre, sep, __VA_ARGS__)
#define priv_prefix_join_25(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_24(pre, sep, __VA_ARGS__)
#define priv_prefix_join_26(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_25(pre, sep, __VA_ARGS__)
#define priv_prefix_join_27(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_26(pre, sep, __VA_ARGS__)
#define priv_prefix_join_28(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_27(pre, sep, __VA_ARGS__)
#define priv_prefix_join_29(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_28(pre, sep, __VA_ARGS__)
#define priv_prefix_join_30(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_29(pre, sep, __VA_ARGS__)
#define priv_prefix_join_31(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_30(pre, sep, __VA_ARGS__)
#define priv_prefix_join_32(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_31(pre, sep, __VA_ARGS__)
#define priv_prefix_join_33(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_32(pre, sep, __VA_ARGS__)
#define priv_prefix_join_34(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_33(pre, sep, __VA_ARGS__)
#define priv_prefix_join_35(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_34(pre, sep, __VA_ARGS__)
#define priv_prefix_join_36(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_35(pre, sep, __VA_ARGS__)
#define priv_prefix_join_37(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_36(pre, sep, __VA_ARGS__)
#define priv_prefix_join_38(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_37(pre, sep, __VA_ARGS__)
#define priv_prefix_join_39(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_38(pre, sep, __VA_ARGS__)
#define priv_prefix_join_40(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_39(pre, sep, __VA_ARGS__)
#define priv_prefix_join_41(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_40(pre, sep, __VA_ARGS__)
#define priv_prefix_join_42(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_41(pre, sep, __VA_ARGS__)
#define priv_prefix_join_43(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_42(pre, sep, __VA_ARGS__)
#define priv_prefix_join_44(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_43(pre, sep, __VA_ARGS__)
#define priv_prefix_join_45(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_44(pre, sep, __VA_ARGS__)
#define priv_prefix_join_46(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_45(pre, sep, __VA_ARGS__)
#define priv_prefix_join_47(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_46(pre, sep, __VA_ARGS__)
#define priv_prefix_join_48(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_47(pre, sep, __VA_ARGS__)
#define priv_prefix_join_49(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_48(pre, sep, __VA_ARGS__)
#define priv_prefix_join_50(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_49(pre, sep, __VA_ARGS__)
#define priv_prefix_join_51(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_50(pre, sep, __VA_ARGS__)
#define priv_prefix_join_52(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_51(pre, sep, __VA_ARGS__)
#define priv_prefix_join_53(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_52(pre, sep, __VA_ARGS__)
#define priv_prefix_join_54(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_53(pre, sep, __VA_ARGS__)
#define priv_prefix_join_55(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_54(pre, sep, __VA_ARGS__)
#define priv_prefix_join_56(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_55(pre, sep, __VA_ARGS__)
#define priv_prefix_join_57(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_56(pre, sep, __VA_ARGS__)
#define priv_prefix_join_58(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_57(pre, sep, __VA_ARGS__)
#define priv_prefix_join_59(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_58(pre, sep, __VA_ARGS__)
#define priv_prefix_join_60(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_59(pre, sep, __VA_ARGS__)
#define priv_prefix_join_61(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_60(pre, sep, __VA_ARGS__)
#define priv_prefix_join_62(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_61(pre, sep, __VA_ARGS__)
#define priv_prefix_join_63(pre, sep, v, ...) priv_join_2(sep, pre, v), priv_prefix_join_62(pre, sep, __VA_ARGS__)

#define priv_prefix_combine(pre, ...) priv_overload(priv_prefix_combine, priv_argc(__VA_ARGS__))(pre, __VA_ARGS__)
#define priv_prefix_concat(pre, ...) priv_overload(priv_prefix_concat, priv_argc(__VA_ARGS__))(pre, __VA_ARGS__)
#define priv_prefix_join(pre, sep, ...) priv_overload(priv_prefix_join, priv_argc(__VA_ARGS__))(pre, sep, __VA_ARGS__)

#endif
