#ifndef GOOLNN_XMACROS_PRIV_SPACE_H
#define GOOLNN_XMACROS_PRIV_SPACE_H

#include "xmacros/priv/overload.h"
#include "xmacros/priv/argc.h"

#define priv_space_0()
#define priv_space_1(v) v
#define priv_space_2(v, ...) v priv_space_1(__VA_ARGS__)
#define priv_space_3(v, ...) v priv_space_2(__VA_ARGS__)
#define priv_space_4(v, ...) v priv_space_3(__VA_ARGS__)
#define priv_space_5(v, ...) v priv_space_4(__VA_ARGS__)
#define priv_space_6(v, ...) v priv_space_5(__VA_ARGS__)
#define priv_space_7(v, ...) v priv_space_6(__VA_ARGS__)
#define priv_space_8(v, ...) v priv_space_7(__VA_ARGS__)
#define priv_space_9(v, ...) v priv_space_8(__VA_ARGS__)
#define priv_space_10(v, ...) v priv_space_9(__VA_ARGS__)
#define priv_space_11(v, ...) v priv_space_10(__VA_ARGS__)
#define priv_space_12(v, ...) v priv_space_11(__VA_ARGS__)
#define priv_space_13(v, ...) v priv_space_12(__VA_ARGS__)
#define priv_space_14(v, ...) v priv_space_13(__VA_ARGS__)
#define priv_space_15(v, ...) v priv_space_14(__VA_ARGS__)
#define priv_space_16(v, ...) v priv_space_15(__VA_ARGS__)
#define priv_space_17(v, ...) v priv_space_16(__VA_ARGS__)
#define priv_space_18(v, ...) v priv_space_17(__VA_ARGS__)
#define priv_space_19(v, ...) v priv_space_18(__VA_ARGS__)
#define priv_space_20(v, ...) v priv_space_19(__VA_ARGS__)
#define priv_space_21(v, ...) v priv_space_20(__VA_ARGS__)
#define priv_space_22(v, ...) v priv_space_21(__VA_ARGS__)
#define priv_space_23(v, ...) v priv_space_22(__VA_ARGS__)
#define priv_space_24(v, ...) v priv_space_23(__VA_ARGS__)
#define priv_space_25(v, ...) v priv_space_24(__VA_ARGS__)
#define priv_space_26(v, ...) v priv_space_25(__VA_ARGS__)
#define priv_space_27(v, ...) v priv_space_26(__VA_ARGS__)
#define priv_space_28(v, ...) v priv_space_27(__VA_ARGS__)
#define priv_space_29(v, ...) v priv_space_28(__VA_ARGS__)
#define priv_space_30(v, ...) v priv_space_29(__VA_ARGS__)
#define priv_space_31(v, ...) v priv_space_30(__VA_ARGS__)
#define priv_space_32(v, ...) v priv_space_31(__VA_ARGS__)
#define priv_space_33(v, ...) v priv_space_32(__VA_ARGS__)
#define priv_space_34(v, ...) v priv_space_33(__VA_ARGS__)
#define priv_space_35(v, ...) v priv_space_34(__VA_ARGS__)
#define priv_space_36(v, ...) v priv_space_35(__VA_ARGS__)
#define priv_space_37(v, ...) v priv_space_36(__VA_ARGS__)
#define priv_space_38(v, ...) v priv_space_37(__VA_ARGS__)
#define priv_space_39(v, ...) v priv_space_38(__VA_ARGS__)
#define priv_space_40(v, ...) v priv_space_39(__VA_ARGS__)
#define priv_space_41(v, ...) v priv_space_40(__VA_ARGS__)
#define priv_space_42(v, ...) v priv_space_41(__VA_ARGS__)
#define priv_space_43(v, ...) v priv_space_42(__VA_ARGS__)
#define priv_space_44(v, ...) v priv_space_43(__VA_ARGS__)
#define priv_space_45(v, ...) v priv_space_44(__VA_ARGS__)
#define priv_space_46(v, ...) v priv_space_45(__VA_ARGS__)
#define priv_space_47(v, ...) v priv_space_46(__VA_ARGS__)
#define priv_space_48(v, ...) v priv_space_47(__VA_ARGS__)
#define priv_space_49(v, ...) v priv_space_48(__VA_ARGS__)
#define priv_space_50(v, ...) v priv_space_49(__VA_ARGS__)
#define priv_space_51(v, ...) v priv_space_50(__VA_ARGS__)
#define priv_space_52(v, ...) v priv_space_51(__VA_ARGS__)
#define priv_space_53(v, ...) v priv_space_52(__VA_ARGS__)
#define priv_space_54(v, ...) v priv_space_53(__VA_ARGS__)
#define priv_space_55(v, ...) v priv_space_54(__VA_ARGS__)
#define priv_space_56(v, ...) v priv_space_55(__VA_ARGS__)
#define priv_space_57(v, ...) v priv_space_56(__VA_ARGS__)
#define priv_space_58(v, ...) v priv_space_57(__VA_ARGS__)
#define priv_space_59(v, ...) v priv_space_58(__VA_ARGS__)
#define priv_space_60(v, ...) v priv_space_59(__VA_ARGS__)
#define priv_space_61(v, ...) v priv_space_60(__VA_ARGS__)
#define priv_space_62(v, ...) v priv_space_61(__VA_ARGS__)
#define priv_space_63(v, ...) v priv_space_62(__VA_ARGS__)

#define priv_space(...)priv_overload(priv_space, priv_argc(__VA_ARGS__))(__VA_ARGS__)

#endif
