#ifndef GOOLNN_XMACROS_PRIV_SUB_H
#define GOOLNN_XMACROS_PRIV_SUB_H

#include "xmacros/priv/overload.h"
#include "xmacros/priv/reverse.h"
#include "xmacros/priv/argc.h"
#include "xmacros/priv/pop.h"

#define priv_sub_front_0(...)
#define priv_sub_front_1(v, ...) v
#define priv_sub_front_2(v, ...) v, priv_sub_front_1(__VA_ARGS__)
#define priv_sub_front_3(v, ...) v, priv_sub_front_2(__VA_ARGS__)
#define priv_sub_front_4(v, ...) v, priv_sub_front_3(__VA_ARGS__)
#define priv_sub_front_5(v, ...) v, priv_sub_front_4(__VA_ARGS__)
#define priv_sub_front_6(v, ...) v, priv_sub_front_5(__VA_ARGS__)
#define priv_sub_front_7(v, ...) v, priv_sub_front_6(__VA_ARGS__)
#define priv_sub_front_8(v, ...) v, priv_sub_front_7(__VA_ARGS__)
#define priv_sub_front_9(v, ...) v, priv_sub_front_8(__VA_ARGS__)
#define priv_sub_front_10(v, ...) v, priv_sub_front_9(__VA_ARGS__)
#define priv_sub_front_11(v, ...) v, priv_sub_front_10(__VA_ARGS__)
#define priv_sub_front_12(v, ...) v, priv_sub_front_11(__VA_ARGS__)
#define priv_sub_front_13(v, ...) v, priv_sub_front_12(__VA_ARGS__)
#define priv_sub_front_14(v, ...) v, priv_sub_front_13(__VA_ARGS__)
#define priv_sub_front_15(v, ...) v, priv_sub_front_14(__VA_ARGS__)
#define priv_sub_front_16(v, ...) v, priv_sub_front_15(__VA_ARGS__)
#define priv_sub_front_17(v, ...) v, priv_sub_front_16(__VA_ARGS__)
#define priv_sub_front_18(v, ...) v, priv_sub_front_17(__VA_ARGS__)
#define priv_sub_front_19(v, ...) v, priv_sub_front_18(__VA_ARGS__)
#define priv_sub_front_20(v, ...) v, priv_sub_front_19(__VA_ARGS__)
#define priv_sub_front_21(v, ...) v, priv_sub_front_20(__VA_ARGS__)
#define priv_sub_front_22(v, ...) v, priv_sub_front_21(__VA_ARGS__)
#define priv_sub_front_23(v, ...) v, priv_sub_front_22(__VA_ARGS__)
#define priv_sub_front_24(v, ...) v, priv_sub_front_23(__VA_ARGS__)
#define priv_sub_front_25(v, ...) v, priv_sub_front_24(__VA_ARGS__)
#define priv_sub_front_26(v, ...) v, priv_sub_front_25(__VA_ARGS__)
#define priv_sub_front_27(v, ...) v, priv_sub_front_26(__VA_ARGS__)
#define priv_sub_front_28(v, ...) v, priv_sub_front_27(__VA_ARGS__)
#define priv_sub_front_29(v, ...) v, priv_sub_front_28(__VA_ARGS__)
#define priv_sub_front_30(v, ...) v, priv_sub_front_29(__VA_ARGS__)
#define priv_sub_front_31(v, ...) v, priv_sub_front_30(__VA_ARGS__)
#define priv_sub_front_32(v, ...) v, priv_sub_front_31(__VA_ARGS__)
#define priv_sub_front_33(v, ...) v, priv_sub_front_32(__VA_ARGS__)
#define priv_sub_front_34(v, ...) v, priv_sub_front_33(__VA_ARGS__)
#define priv_sub_front_35(v, ...) v, priv_sub_front_34(__VA_ARGS__)
#define priv_sub_front_36(v, ...) v, priv_sub_front_35(__VA_ARGS__)
#define priv_sub_front_37(v, ...) v, priv_sub_front_36(__VA_ARGS__)
#define priv_sub_front_38(v, ...) v, priv_sub_front_37(__VA_ARGS__)
#define priv_sub_front_39(v, ...) v, priv_sub_front_38(__VA_ARGS__)
#define priv_sub_front_40(v, ...) v, priv_sub_front_39(__VA_ARGS__)
#define priv_sub_front_41(v, ...) v, priv_sub_front_40(__VA_ARGS__)
#define priv_sub_front_42(v, ...) v, priv_sub_front_41(__VA_ARGS__)
#define priv_sub_front_43(v, ...) v, priv_sub_front_42(__VA_ARGS__)
#define priv_sub_front_44(v, ...) v, priv_sub_front_43(__VA_ARGS__)
#define priv_sub_front_45(v, ...) v, priv_sub_front_44(__VA_ARGS__)
#define priv_sub_front_46(v, ...) v, priv_sub_front_45(__VA_ARGS__)
#define priv_sub_front_47(v, ...) v, priv_sub_front_46(__VA_ARGS__)
#define priv_sub_front_48(v, ...) v, priv_sub_front_47(__VA_ARGS__)
#define priv_sub_front_49(v, ...) v, priv_sub_front_48(__VA_ARGS__)
#define priv_sub_front_50(v, ...) v, priv_sub_front_49(__VA_ARGS__)
#define priv_sub_front_51(v, ...) v, priv_sub_front_50(__VA_ARGS__)
#define priv_sub_front_52(v, ...) v, priv_sub_front_51(__VA_ARGS__)
#define priv_sub_front_53(v, ...) v, priv_sub_front_52(__VA_ARGS__)
#define priv_sub_front_54(v, ...) v, priv_sub_front_53(__VA_ARGS__)
#define priv_sub_front_55(v, ...) v, priv_sub_front_54(__VA_ARGS__)
#define priv_sub_front_56(v, ...) v, priv_sub_front_55(__VA_ARGS__)
#define priv_sub_front_57(v, ...) v, priv_sub_front_56(__VA_ARGS__)
#define priv_sub_front_58(v, ...) v, priv_sub_front_57(__VA_ARGS__)
#define priv_sub_front_59(v, ...) v, priv_sub_front_58(__VA_ARGS__)
#define priv_sub_front_60(v, ...) v, priv_sub_front_59(__VA_ARGS__)
#define priv_sub_front_61(v, ...) v, priv_sub_front_60(__VA_ARGS__)
#define priv_sub_front_62(v, ...) v, priv_sub_front_61(__VA_ARGS__)
#define priv_sub_front_63(v, ...) v, priv_sub_front_62(__VA_ARGS__)

#define priv_sub_front(n, ...) priv_overload(priv_sub_front, n)(__VA_ARGS__)
#define priv_sub_back(n, ...) priv_reverse(priv_sub_front(n, priv_reverse(__VA_ARGS__)))

#define priv_sub(i, j, ...) priv_pop_front(i, priv_sub_front(j, __VA_ARGS__))

#endif
