#ifndef GOOLNN_XMACROS_PRIV_WRAP_H
#define GOOLNN_XMACROS_PRIV_WRAP_H

#include "xmacros/priv/overload.h"
#include "xmacros/priv/argc.h"

#define priv_wrap_0()
#define priv_wrap_1(v) (v)
#define priv_wrap_2(v, ...) (v), priv_wrap_1(__VA_ARGS__)
#define priv_wrap_3(v, ...) (v), priv_wrap_2(__VA_ARGS__)
#define priv_wrap_4(v, ...) (v), priv_wrap_3(__VA_ARGS__)
#define priv_wrap_5(v, ...) (v), priv_wrap_4(__VA_ARGS__)
#define priv_wrap_6(v, ...) (v), priv_wrap_5(__VA_ARGS__)
#define priv_wrap_7(v, ...) (v), priv_wrap_6(__VA_ARGS__)
#define priv_wrap_8(v, ...) (v), priv_wrap_7(__VA_ARGS__)
#define priv_wrap_9(v, ...) (v), priv_wrap_8(__VA_ARGS__)
#define priv_wrap_10(v, ...) (v), priv_wrap_9(__VA_ARGS__)
#define priv_wrap_11(v, ...) (v), priv_wrap_10(__VA_ARGS__)
#define priv_wrap_12(v, ...) (v), priv_wrap_11(__VA_ARGS__)
#define priv_wrap_13(v, ...) (v), priv_wrap_12(__VA_ARGS__)
#define priv_wrap_14(v, ...) (v), priv_wrap_13(__VA_ARGS__)
#define priv_wrap_15(v, ...) (v), priv_wrap_14(__VA_ARGS__)
#define priv_wrap_16(v, ...) (v), priv_wrap_15(__VA_ARGS__)
#define priv_wrap_17(v, ...) (v), priv_wrap_16(__VA_ARGS__)
#define priv_wrap_18(v, ...) (v), priv_wrap_17(__VA_ARGS__)
#define priv_wrap_19(v, ...) (v), priv_wrap_18(__VA_ARGS__)
#define priv_wrap_20(v, ...) (v), priv_wrap_19(__VA_ARGS__)
#define priv_wrap_21(v, ...) (v), priv_wrap_20(__VA_ARGS__)
#define priv_wrap_22(v, ...) (v), priv_wrap_21(__VA_ARGS__)
#define priv_wrap_23(v, ...) (v), priv_wrap_22(__VA_ARGS__)
#define priv_wrap_24(v, ...) (v), priv_wrap_23(__VA_ARGS__)
#define priv_wrap_25(v, ...) (v), priv_wrap_24(__VA_ARGS__)
#define priv_wrap_26(v, ...) (v), priv_wrap_25(__VA_ARGS__)
#define priv_wrap_27(v, ...) (v), priv_wrap_26(__VA_ARGS__)
#define priv_wrap_28(v, ...) (v), priv_wrap_27(__VA_ARGS__)
#define priv_wrap_29(v, ...) (v), priv_wrap_28(__VA_ARGS__)
#define priv_wrap_30(v, ...) (v), priv_wrap_29(__VA_ARGS__)
#define priv_wrap_31(v, ...) (v), priv_wrap_30(__VA_ARGS__)
#define priv_wrap_32(v, ...) (v), priv_wrap_31(__VA_ARGS__)
#define priv_wrap_33(v, ...) (v), priv_wrap_32(__VA_ARGS__)
#define priv_wrap_34(v, ...) (v), priv_wrap_33(__VA_ARGS__)
#define priv_wrap_35(v, ...) (v), priv_wrap_34(__VA_ARGS__)
#define priv_wrap_36(v, ...) (v), priv_wrap_35(__VA_ARGS__)
#define priv_wrap_37(v, ...) (v), priv_wrap_36(__VA_ARGS__)
#define priv_wrap_38(v, ...) (v), priv_wrap_37(__VA_ARGS__)
#define priv_wrap_39(v, ...) (v), priv_wrap_38(__VA_ARGS__)
#define priv_wrap_40(v, ...) (v), priv_wrap_39(__VA_ARGS__)
#define priv_wrap_41(v, ...) (v), priv_wrap_40(__VA_ARGS__)
#define priv_wrap_42(v, ...) (v), priv_wrap_41(__VA_ARGS__)
#define priv_wrap_43(v, ...) (v), priv_wrap_42(__VA_ARGS__)
#define priv_wrap_44(v, ...) (v), priv_wrap_43(__VA_ARGS__)
#define priv_wrap_45(v, ...) (v), priv_wrap_44(__VA_ARGS__)
#define priv_wrap_46(v, ...) (v), priv_wrap_45(__VA_ARGS__)
#define priv_wrap_47(v, ...) (v), priv_wrap_46(__VA_ARGS__)
#define priv_wrap_48(v, ...) (v), priv_wrap_47(__VA_ARGS__)
#define priv_wrap_49(v, ...) (v), priv_wrap_48(__VA_ARGS__)
#define priv_wrap_50(v, ...) (v), priv_wrap_49(__VA_ARGS__)
#define priv_wrap_51(v, ...) (v), priv_wrap_50(__VA_ARGS__)
#define priv_wrap_52(v, ...) (v), priv_wrap_51(__VA_ARGS__)
#define priv_wrap_53(v, ...) (v), priv_wrap_52(__VA_ARGS__)
#define priv_wrap_54(v, ...) (v), priv_wrap_53(__VA_ARGS__)
#define priv_wrap_55(v, ...) (v), priv_wrap_54(__VA_ARGS__)
#define priv_wrap_56(v, ...) (v), priv_wrap_55(__VA_ARGS__)
#define priv_wrap_57(v, ...) (v), priv_wrap_56(__VA_ARGS__)
#define priv_wrap_58(v, ...) (v), priv_wrap_57(__VA_ARGS__)
#define priv_wrap_59(v, ...) (v), priv_wrap_58(__VA_ARGS__)
#define priv_wrap_60(v, ...) (v), priv_wrap_59(__VA_ARGS__)
#define priv_wrap_61(v, ...) (v), priv_wrap_60(__VA_ARGS__)
#define priv_wrap_62(v, ...) (v), priv_wrap_61(__VA_ARGS__)
#define priv_wrap_63(v, ...) (v), priv_wrap_62(__VA_ARGS__)

#define priv_wrap(...) priv_overload(priv_wrap, priv_argc(__VA_ARGS__))(__VA_ARGS__)

#endif
