#ifndef GOOLNN_XMACROS_PRIV_ZIP_H
#define GOOLNN_XMACROS_PRIV_ZIP_H

#include <xmacros/priv/overload.h>
#include <xmacros/priv/argn.h>
#include <xmacros/priv/argc.h>
#include <xmacros/priv/pop.h>

#define priv_apply_zip(a, b) priv_first a ## priv_first b

#define priv_zip_0()
#define priv_zip_1(a, b) priv_apply_zip(a, b)
#define priv_zip_2(a, b) priv_apply_zip(a, b), priv_zip_1((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_3(a, b) priv_apply_zip(a, b), priv_zip_2((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_4(a, b) priv_apply_zip(a, b), priv_zip_3((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_5(a, b) priv_apply_zip(a, b), priv_zip_4((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_6(a, b) priv_apply_zip(a, b), priv_zip_5((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_7(a, b) priv_apply_zip(a, b), priv_zip_6((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_8(a, b) priv_apply_zip(a, b), priv_zip_7((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_9(a, b) priv_apply_zip(a, b), priv_zip_8((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_10(a, b) priv_apply_zip(a, b), priv_zip_9((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_11(a, b) priv_apply_zip(a, b), priv_zip_10((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_12(a, b) priv_apply_zip(a, b), priv_zip_11((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_13(a, b) priv_apply_zip(a, b), priv_zip_12((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_14(a, b) priv_apply_zip(a, b), priv_zip_13((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_15(a, b) priv_apply_zip(a, b), priv_zip_14((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_16(a, b) priv_apply_zip(a, b), priv_zip_15((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_17(a, b) priv_apply_zip(a, b), priv_zip_16((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_18(a, b) priv_apply_zip(a, b), priv_zip_17((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_19(a, b) priv_apply_zip(a, b), priv_zip_18((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_20(a, b) priv_apply_zip(a, b), priv_zip_19((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_21(a, b) priv_apply_zip(a, b), priv_zip_20((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_22(a, b) priv_apply_zip(a, b), priv_zip_21((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_23(a, b) priv_apply_zip(a, b), priv_zip_22((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_24(a, b) priv_apply_zip(a, b), priv_zip_23((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_25(a, b) priv_apply_zip(a, b), priv_zip_24((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_26(a, b) priv_apply_zip(a, b), priv_zip_25((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_27(a, b) priv_apply_zip(a, b), priv_zip_26((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_28(a, b) priv_apply_zip(a, b), priv_zip_27((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_29(a, b) priv_apply_zip(a, b), priv_zip_28((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_30(a, b) priv_apply_zip(a, b), priv_zip_29((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_31(a, b) priv_apply_zip(a, b), priv_zip_30((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_32(a, b) priv_apply_zip(a, b), priv_zip_31((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_33(a, b) priv_apply_zip(a, b), priv_zip_32((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_34(a, b) priv_apply_zip(a, b), priv_zip_33((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_35(a, b) priv_apply_zip(a, b), priv_zip_34((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_36(a, b) priv_apply_zip(a, b), priv_zip_35((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_37(a, b) priv_apply_zip(a, b), priv_zip_36((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_38(a, b) priv_apply_zip(a, b), priv_zip_37((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_39(a, b) priv_apply_zip(a, b), priv_zip_38((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_40(a, b) priv_apply_zip(a, b), priv_zip_39((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_41(a, b) priv_apply_zip(a, b), priv_zip_40((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_42(a, b) priv_apply_zip(a, b), priv_zip_41((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_43(a, b) priv_apply_zip(a, b), priv_zip_42((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_44(a, b) priv_apply_zip(a, b), priv_zip_43((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_45(a, b) priv_apply_zip(a, b), priv_zip_44((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_46(a, b) priv_apply_zip(a, b), priv_zip_45((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_47(a, b) priv_apply_zip(a, b), priv_zip_46((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_48(a, b) priv_apply_zip(a, b), priv_zip_47((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_49(a, b) priv_apply_zip(a, b), priv_zip_48((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_50(a, b) priv_apply_zip(a, b), priv_zip_49((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_51(a, b) priv_apply_zip(a, b), priv_zip_50((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_52(a, b) priv_apply_zip(a, b), priv_zip_51((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_53(a, b) priv_apply_zip(a, b), priv_zip_52((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_54(a, b) priv_apply_zip(a, b), priv_zip_53((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_55(a, b) priv_apply_zip(a, b), priv_zip_54((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_56(a, b) priv_apply_zip(a, b), priv_zip_55((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_57(a, b) priv_apply_zip(a, b), priv_zip_56((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_58(a, b) priv_apply_zip(a, b), priv_zip_57((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_59(a, b) priv_apply_zip(a, b), priv_zip_58((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_60(a, b) priv_apply_zip(a, b), priv_zip_59((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_61(a, b) priv_apply_zip(a, b), priv_zip_60((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_62(a, b) priv_apply_zip(a, b), priv_zip_61((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))
#define priv_zip_63(a, b) priv_apply_zip(a, b), priv_zip_62((priv_pop_front(1, priv_unpack(a))), (priv_pop_front(1, priv_unpack(b))))

#define priv_zip(a, b) priv_overload(priv_zip, priv_argc(priv_unpack(a)))(a, b)

#endif
